apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher
  labels:
    app: rancher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rancher
  template:
    metadata:
      labels:
        app: rancher
    spec:
      containers:
        - name: rancher
          image: ruanbekker/logos:rancher
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: rancher
spec:
  selector:
    app: rancher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30010
  type: NodePort
