apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher
  labels:
    app: rancher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rancher
  template:
    metadata:
      labels:
        app: rancher
    spec:
      containers:
        - name: rancher
          image: ruanbekker/logos:rancher
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: rancher
spec:
  selector:
    app: rancher
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: rancher.ingress.ddnsfree.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rancher
                port:
                  number: 80